server:
  port: 8080
  
spring:
  profiles:
    active: "dev"
    
---

spring:
  profiles: dev

  liquibase:
    check-change-log-location: true
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    
  jpa:
    database: h2
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:bd_sw_api;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    hikari:
      pool-name: swApiPoolCP
      minimum-idle: 5
      maximum-pool-size: 20
      
---

spring:
  profiles: teste
  
  liquibase:
    enabled: false
    
  jpa:
    database: h2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      
  datasource:
    url: jdbc:h2:mem:bd_sw_api;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      
---

spring:
  profiles: integracao
  
  liquibase:
    enabled: false
    